# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ol-base-oivindloe-light
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v5
    - name: Set up uv
      uses: astral-sh/setup-uv@v8.3.2
      with:
        version: "latest"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --all-extras --all-groups
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run pre-commit run pylint --all-files
    - name: MyPy
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run pre-commit run mypy --all-files
    - name: Test
      run: |
        ./scripts/test.sh
